### PR TITLE
Capstone Project Pull Request

### PR DESCRIPTION
**Pull request by alvaropazz**
- This project consists of the main, chat details and chats page of the social network idea project for the Capstone of the HTML and CSS3 module.
- These are 3 pages optimized for the iPhone X, iPad Pro and Desktop.
- Two of the HTML archives (index.html and conversations.html) have 3 breakpoints for responsiveness, phone, tablet and desktop.
- The HTML archive chats.html doesn't have responsiveness beyond phone because it'd be redundant, given that the chat details and chat page are the same for tablet and desktop.

### CODE REVIEW

**Comment by davitomix** [comment]
Pull Request under review [...] TSE David Elí 👨‍🚀

**Comment by alvaropazz** [comment]
Capstone Changes:

*Corrected links between pages
*Corrected tag for the navbar
*Updated live version link

** I do not understand this wording: " I notice the struggle you did on organize the semantic tags in a good way. The HTML doesn't have validation issues and you reuse your CSS classes through the different pages."
** This "suggestion": "I recommend you implement more colors and customize the project more with specific details that make your project looks unique" does not make any sense to me. Sometimes more is less, and I think adding more colors to the project would make it look bad.
** I didn't include an H1 tag because I don't think there's a place where it'd be appropriate. However, I  included plenty of H2 tags.

**Comment by alvaropazz** [comment]
Capstone Changes:

*Added H1 on top of each page

**Comment by alvaropazz** [comment]
Review:

"<h3>Kindly address these comments and add their respective links so navigation becomes easier and simple</h3> <ul> <li>- The person detail page, with a link to the next/previous person detail and a link to the chat page</li> <li>The chat page, with a list of chats that link to the chat detail page</li> </ul>"

*I already added navigation between pages. 
*Again, it is disrespectful for me and my time the fact that you guys keep on adding items when you haven't even checked that they've been already added.

**Comment by alvaropazz** [comment]
Code review changes implemented.

**Pull request merged**
